### ISSUE TITLE
Unable to upload offline survey results getting maximum request length exceeded error.

### ISSUE THREAD

**Issue by veereshms** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#7]
Unable to upload offline survey results getting maximum request length exceeded error, refer attached screenshot.
![3298 screenshot_20170710-154706](https://user-images.githubusercontent.com/26476914/28052340-3ef54e74-6628-11e7-8ce5-9f8f26df8ab1.png)

**Comment by veereshms** [comment]
This issue is happening for attached script and not for all scripts, please find attached .opgs file for your reference.
[AllFiledTypesSumeethika_16052017.zip](https://github.com/OnePointGlobal/OnePoint-Global-MySurveys-App-Android/files/1151736/AllFiledTypesSumeethika_16052017.zip)

**Comment by vivek-onepoint** [comment]
Fixed in Development server.

**Comment by dinesh-opg** [comment]
This issue is fixed

**Comment by veereshms** [comment]
Issue is still present.

![1054 screenshot_20170906-130400](https://user-images.githubusercontent.com/26476914/30100222-b9e97ce0-9305-11e7-97bf-a0e34b68d1e5.png)

**Comment by dinesh-opg** [comment]
This is the error message we are getting from backend.

**Comment by vivek-onepoint** [comment]
This is working fine in dev server (Tested with the script given by veeresh). There was some issue in configuration which has been changed and now that same script works fine in staging too.

**Comment by veereshms** [comment]
Now the results are uploading but progress bar is not moving while uploading.

**Comment by veereshms** [comment]
Issue is fixed and same has been verified.
